### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by maicol07** [kazuyaujihara/ChemFormatter#2]
Hi,
can I help you with plugin translation?

**Comment by k-ujihara** [comment]
Yes, please.

**Comment by maicol07** [comment]
@kazuyaujihara ok, I would like to translate into Italian. How can I do this?

_Inviato dal mio ZenFone 3 (ZE520KL) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k-ujihara** [comment]
What do you want to translate in ChemFormatter?  I am welcome to accept your request. 
I am also accept one-by-one translation table.

**Comment by maicol07** [comment]
@kazuyaujihara I would like to translate command strings. Can you provide me this list or theEfile where these strings are contained?

_Inviato dal mio ZenFone 3 (ZE520KL) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by k-ujihara** [comment]
I will make Japanese translation in the near future. After that, post your PR.

**Comment by k-ujihara** [comment]
I made [a brunch for internationalization](https://github.com/kazuyaujihara/ChemFormatter/tree/i18n).
Add Italian translated words to [Resources.it.resx](https://github.com/kazuyaujihara/ChemFormatter/blob/i18n/ChemFormatter.Lib/Properties/Resources.it.resx) like [Resources.resx](https://github.com/kazuyaujihara/ChemFormatter/blob/i18n/ChemFormatter.Lib/Properties/Resources.resx) or [Resources.ja.resx](https://github.com/kazuyaujihara/ChemFormatter/blob/i18n/ChemFormatter.Lib/Properties/Resources.ja.resx).
And then make a pull request.

**Comment by maicol07** [comment]
Done with PR #3
